_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/ttfnet_res50vd.yml',
  '_base_/ttfnet_reader.yml',
]
weights: output/ttfnet_resnet50vd_1x_coco/model_final
