_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_2x.yml',
  '_base_/ttfnet_resnet18+transformer+mulcls+alpha+cca.yml',
  '_base_/ttfnet_reader_mulcls.yml',
]
weights: output/ttfnet_res18_2x_coco_ema_sync+trans+mulcls+alpha_IoU+cca/model_final