_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/ttfnet_resnet18+transformer+mulcls+dcnv3.yml',
  '_base_/ttfnet_reader_mulcls.yml',
]
weights: output/ttfnet_res18_1x_coco_ema_sync+trans+mulcls+dcnv3/model_final
