_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x_adamw.yml',
  '_base_/ttfnet_mobilevitv1.yml',
  '_base_/ttfnet_reader.yml',
]
weights: output/ttfnet_mobilevitv1_1x_coco_adamw/model_final
