_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/ttfnet_resmobilevitv1_rezero.yml',
  '_base_/ttfnet_reader.yml',
]

# custom_black_list:
#   - pow
#   - elementwise_pow

weights: output/ttfnet_resmobilevitv1_rezero_1x_coco_bn/model_final