epoch: 12

LearningRate:
  base_lr: 0.015
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [8, 11]
  - !LinearWarmup
    start_factor: 0.2
    steps: 500

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  optimizer:
    type: AdamW
    weight_decay: 0.0001
  regularizer:
    factor: 0.0004
    type: L2
