epoch: 24

LearningRate:
  base_lr: 0.015
  schedulers:
  - !PiecewiseDecay
    gamma: 0.9999999
    milestones: [8, 11]
  - !LinearWarmup
    start_factor: 0.2
    steps: 500

OptimizerBuilder:
  # clip_grad_by_norm: 1.236
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0004
    type: L2
