worker_num: 8
input_height: &input_height 512
input_width: &input_width 512
input_size: &input_size [*input_height, *input_width]
mosaic_epoch: &mosaic_epoch 10 # last 2 epochs close mosaic, totally 12 epochs as default

TrainReader:
  sample_transforms:
    - Decode: {}
    - MosaicPerspective: {mosaic_prob: 1.0, target_size: *input_size}
    - RandomHSV: {hgain: 0.015, sgain: 0.7, vgain: 0.4}
    - RandomFlip: {}
    - Resize: {interp: 1, target_size: *input_size, keep_ratio: False}
  batch_transforms:
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
    - Gt2TTFTarget_MULTI_CLS: {down_ratio: 4}
  batch_size: 32
  shuffle: true
  drop_last: true
  use_shared_memory: true
  collate_batch: True
  mosaic_epoch: *mosaic_epoch

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *input_size, keep_ratio: True, interp: 1}
    - Pad: {size: *input_size, fill_value: [114., 114., 114.]}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 32
  drop_last: false

TestReader:
  inputs_def:
    image_shape: [3, 512, 512]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *input_size, keep_ratio: True, interp: 1}
    - Pad: {size: *input_size, fill_value: [114., 114., 114.]}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 32
  fuse_normalize: False