architecture: TTFNet
# pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/DarkNet53_pretrained.pdparams

TTFNet:
  backbone: MobileViTV1 
  neck: TTFFPN
  ttf_head: TTFHead
  post_process: BBoxPostProcess

MobileViTV1:
  pretrained: true
  arch_name: MobileViT_XS

TTFFPN:
  planes: [256, 128, 64]
  shortcut_num: [3, 2, 1]
  encoder_layer:
    name: TTFTransformerLayer
    d_model: 96
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.
    activation: 'gelu'

TTFHead:
  hm_loss:
    name: CTFocalLoss
    loss_weight: 1.
  wh_loss:
    name: alpha_DIouLoss
    loss_weight: 5.
    alpha: 3
    # reduction: sum

BBoxPostProcess:
  decode:
    name: TTFBox
    max_per_img: 100
    score_thresh: 0.01
    down_ratio: 4
