architecture: TTFNet
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_v2_pretrained.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

TTFNet:
  backbone: ResNet
  neck: TTFFPN
  ttf_head: TTFHead
  post_process: BBoxPostProcess

ResNet:
  # index 0 stands for res2
  depth: 50
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [0, 1, 2, 3]
  lr_mult_list: [0.1, 0.1, 0.1, 0.1]
  num_stages: 4
  freeze_stem_only: True

TTFFPN:
  planes: [256, 128, 64]
  shortcut_num: [3, 2, 1]
  dcnv3_neck: false
  encoder_layer:
    name: TTFTransformerLayer
    d_model: 2048
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.
    activation: 'gelu'
    rezero: false

TTFHead:
  hm_loss:
    name: CTFocalLoss
    loss_weight: 1.
  wh_loss:
    name: GIoULoss
    loss_weight: 5.
    reduction: sum
  hm_decay_iter: -1 # 不先优化 hm_loss

BBoxPostProcess:
  decode:
    name: TTFBox
    max_per_img: 100
    score_thresh: 0.01
    down_ratio: 4
