architecture: TTFNet
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/DarkNet53_pretrained.pdparams
# norm_type: sync_bn
# use_ema: true
# ema_decay: 0.9998

TTFNet:
  backbone: ResNet
  neck: TTFFPN
  ttf_head: TTFHead
  post_process: BBoxPostProcess

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet18_vd_pretrained.pdparams
ResNet:
  depth: 18
  variant: d
  return_idx: [0, 1, 2, 3]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.

TTFFPN:
  planes: [256, 128, 64]
  shortcut_num: [3, 2, 1]
  dcnv3_neck: false
  use_encoder_idx: []
  # encoder_layer:
  #   name: TTFTransformerLayer
  #   d_model: 1024
  #   nhead: 8
  #   dim_feedforward: 256
  #   dropout: 0.
  #   activation: 'gelu'
  #   rezero: false

TTFHead:
  hm_loss:
    name: CTFocalLoss
    loss_weight: 1.
  wh_loss:
    name: GIoULoss
    loss_weight: 5.
    reduction: sum
  # mul_cls_loss:
  #   name: MultiLabelLoss
  #   epsilon: 0.1
  #   class_num: 80
  hm_decay_iter: -1 # 不先优化 hm_loss

BBoxPostProcess:
  decode:
    name: TTFBox
    max_per_img: 100
    score_thresh: 0.01
    down_ratio: 4
