architecture: TTFNet
# pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/DarkNet53_pretrained.pdparams
# norm_type: sync_bn
# use_ema: true
# ema_decay: 0.9998

TTFNet:
  backbone: ResMobileViTV1 
  neck: TTFFPN
  ttf_head: TTFHead
  post_process: BBoxPostProcess

ResMobileViTV1:
  pretrained: true
  arch_name: MobileViT_XS
  rezero: true

TTFFPN:
  planes: [256, 128, 64]
  shortcut_num: [3, 2, 1]
  encoder_layer:
    name: TTFTransformerLayer
    d_model: 96
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.
    activation: 'gelu'
    rezero: true
    
TTFHead:
  hm_loss:
    name: CTFocalLoss
    loss_weight: 1.
  wh_loss:
    name: GIoULoss
    loss_weight: 5.
    reduction: sum

BBoxPostProcess:
  decode:
    name: TTFBox
    max_per_img: 100
    score_thresh: 0.01
    down_ratio: 4
